### ISSUE TITLE
Crystal Run

### ISSUE THREAD

**Issue by crisward** [f/guardian#13]
I'd like to use this to run a crystal app, then restart it on file change.

How do I do that...?

``` yml
files: ./**/*.cr
run: crystal run ./src/myapp.cr

---
files: ./shard.yml
run: crystal deps
```

This just runs on the first change, then never again, presumably it needs to kill the process, then call run again, any ideas?

Thanks!

**Comment by marceloboeira** [comment]
@crisward I'm going to check, but as far as I remember it should be running on every change.

But let me ask you first:
1) Which version are you using?
2) If you run the command by yourself, the process finishes correctly?

I haven't started writing functional tests yet, so it is hard to track bugs.

**Comment by crisward** [comment]
`crystal run ./src/myapp.cr` doesn't exit when I run it, because it compiles and runs. I have to ctrl+c to exit it.

Crystal version - `Crystal 0.18.7 [68783f1] (2016-07-03)`
guardian - `v0.0.3`

Thanks for your help.

**Comment by jwoertink** [comment]
I'm looking to do this too. With [Guard](https://github.com/guard/guard) you have start and stop methods for the plugins like my [guard-kemal](https://github.com/jwoertink/guard-kemal/blob/master/lib/guard/kemal.rb#L13). I think this is a bit much though. Since we have a `.guardian.yml`, maybe there can just be an extra key like `start` that you can put the script you want to run.

In my case, it would look something like

``` yml
start: crystal app.cr
files: ./**/*.cr
run: crystal app.cr
```

Running `./guardian` would first fun app.cr (which would boot kemal), and then show that guardian is on duty. Once and crystal file was updated in the subdirectory, it would re-run the `app.cr`.

**Comment by samueleaton** [comment]
I've been using guardian too and was looking for this feature. I wrote a small tool that _only_ starts your app and watches for changes and restarts your app, called [Sentry](https://github.com/samueleaton/sentry). 

It is nowhere near as robust as Guardian and just fulfills this single use case. I rely on Guardian for other tasks (e.g. watching and building my css, watching client-side javascript files, installing deps if my `shard.yml` changes, etc.)

**Comment by nulty** [comment]
I've been looking into this myself and it would seem that this is not the responsibility of this library/app. It is better to use a process manager to manage both `crystal run` and `guardian`

Use foreman or overmind to manage both of these process separately.
I don't think foreman can restart processes though. I use overmind.

https://github.com/DarthSim/overmind

## [Procfile](https://devcenter.heroku.com/articles/procfile):
```
web: crystal run src/my_app.cr
guardian: guardian
```

## guardian.yml
```
files: ./**/*.cr
run: overmind restart web
---
files: ./shard.yml
run: shards install

```
## Running process manager 
```
nulty@precision-5530:~/Code/mine/crystal-code/my_app$ overmind s
system   | Tmux socket name: overmind-my_app-P1qRVm3d_pcNclROq4f8-H
system   | Tmux session ID: my_app
system   | Listening at /home/nulty/Code/mine/crystal-code/my_app/.overmind.sock
web      | Started with pid 23495...
guardian | Started with pid 23493...
guardian | 💂  Guardian is on duty!
web      | [development] Kemal is ready to lead at http://0.0.0.0:3000
guardian | ± ./src/service/app_client.cr
guardian | └ 14 insertions(+), 7 deletions(-)
guardian | $ overmind restart web
web      | Interrupting...
web      | Kemal is going to take a rest!
web      | Exited
web      | Restarting...
web      | [development] Kemal is ready to lead at http://0.0.0.0:3000
```

I'd suggest this issue be closed

**Comment by crisward** [comment]
It's ok by me... not used crystal for a while (this issue is 4 years old). I seem to remember we ended up using sentry https://github.com/faustinoaq/sentry-run though that's also not been touched in a while.
