### ISSUE TITLE
[linux] emoji "Guardian is on duty" is not properly displayed

### ISSUE THREAD

**Issue by fpeterschmitt** [f/guardian#21]
Hello,

I'm using the well-known `gnome-terminal` terminal emulator and the emoji isn't displayed. Could we avoid that kind of "exotic" chars?

Thanks

**Comment by wout** [comment]
Isn't that emoji-font related? I'm on elementary OS using Tilix and Terminal and they both display it properly:

![image](https://user-images.githubusercontent.com/107324/77536259-fcdfe180-6e93-11ea-99c2-78abd55acc17.png)

**Comment by f1reflyyyylmao** [comment]
It totally is. While I agree that emojis shouldn't be in terminal applications, this issue is on Lerians side. He just has to properly set up his fonts and check if gnome-terminal supports emojis or filters them on purpose.

**Comment by fpeterschmitt** [comment]
Thanks for answer, however i don't use guardian anymore so i'm just going to close this issue :)

If someone has the answer regarding the font to use, it could eventually be useful for the next person coming to this issue, on my side, i'm out ^.^

**Comment by fpeterschmitt** [comment]
Actually, i gave it a shot, by curiosity. I had the emoji, and i *think* it could come from some `fonts-noto*` package (on ubuntu at least) :)

**Comment by wout** [comment]
@Leryan I remember I had some issues a while back on Pop!_OS, which is very close to Ubuntu, and it had to do with the `fonts-noto` package too. So, they probably fixed it. :)
