### ISSUE TITLE
Update Guardian's GitHub description

### ISSUE THREAD

**Issue by naltun** [f/guardian#3]
`Guardian watches over your files and run assigned tasks` should be changed to `Guardian watches over your files and runs assigned tasks`, in order to keep the grammar consistent. :)

**Comment by f** [comment]
Can you open a PR?

**Comment by naltun** [comment]
:+1: Check Pull Requests.

**Comment by marceloboeira** [comment]
@naltun thanks!

**Comment by naltun** [comment]
@marceloboeira Your welcome!
