### ISSUE TITLE
Provide a command line argument to disable color output

### ISSUE THREAD

**Issue by Hentioe** [f/guardian#30]
Hello, I am a VIM user. In some cases, ANSI colors are not displayed correctly:

![image](https://user-images.githubusercontent.com/13946976/55199443-08eb8180-51f5-11e9-9739-6392900036a1.png)

Can you accept that I might initiate a related Pull Request?

**Comment by f** [comment]
It would be awesome if you open a PR :)

**Comment by Hentioe** [comment]
Someone has already committed the relevant code, so fast. 😂
