### ISSUE TITLE
Keep output clean for readablility.

### ISSUE THREAD

**Issue by wout** [f/guardian#34]
I love guardian and use it in all my projects to run ameba and specs. But often, the leading `>` (introduced [here](https://github.com/f/guardian/blob/master/src/guardian/watcher.cr#L84)) gets in the way. Especially when using Webmock for example:

```crystal
...
>           You can stub this request with the following snippet:
>           
>           WebMock.stub(:get, "https://apisandbox.packlink.com/v1/shipments/123").
>             to_return(body: "")
>           
>            (WebMock::NetConnectNotAllowedError)
...
```

Often, I wait for the spec to fail and copy the snippet provided by Webmock, but this always includes the leading `>`. I think we can leave it out and even reduce the number of spaces.

Another thing that bothers me a bit is the filename marked in red:

![image](https://user-images.githubusercontent.com/107324/77532784-7de7aa80-6e8d-11ea-893f-3e662d37baf4.png)

Red should only be used with failures, so I think `:cyan` would be much better.

**Comment by marceloboeira** [comment]
Solved by #36
